name = "orbitlink-gs2-fiap"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-27"

[[d1_databases]]
binding = "DB"
database_name = "orbitlink_db"
database_id = "2783a9de-924a-4df7-94d4-c487e1ceef3a"
