name = "orbitlink-gs2-fiap"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-27"

[[d1_databases]]
binding = "DB"
database_name = "hss_roi_db"
database_id = "867e174b-291a-47d0-8964-2e8d4fa2cc84"
